version = 0.1
["wallet-gateway/.env.production.json".deploy.parameters]
stack_name = "wallet-gateway"
resolve_s3 = true
s3_prefix = "wallet-gateway"
region = "us-east-2"
profile = "local-developer-kangze-prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
