AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wallet-gateway

  Sample SAM Template for wallet-gateway

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Tracing: Active
    Environment:
      # Variables: 
      #   WALLET_GATEWAY_BASE64_KEY: 'eyJhY2Nlc3NLZXkiOiJBS0lBWEIyTFVSVzNTNEUySkVQRSIsInNlY3JldEtleSI6IlFTR01VbkZJem5Ib0ViYWQ4K2NWL2JrMDd0MkRFSERDL2ZPaTBVYU0ifQ==' # // the right way to do this is using secretsmanager
      #   GCP_KEYFILE_BASE64: 'eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6Im1pbGtzaGFrZS1kZXYtZmFmNzciLCJwcml2YXRlX2tleV9pZCI6IjE3NDQwNDg1NTliNjQ5Y2ZkZjM3NzY0NDgwMWU5ODQ2ZjJhMDYxY2MiLCJwcml2YXRlX2tleSI6Ii0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDaExaa1pZR1dNWTJRT1xuNjBUKzZHZHFiR0Q5bGl2QkJmMEY5cGlPVjZnc2NNUDlpTjVBUGpOYXJxVHpLRmtGWldEN1BYQ2RybU5BYU1ONVxud3Z3U3BxaC8vK0RIakdhcE5JNXNlUFh1Q1Z2VUpyZ0J1MFVSNlByZXpyODI1ZUwrSkQ3N3B3eUZ2REIyemhsalxuN3dFM1RDZUFkYVVuZmpBMHR5OHpBeU43T2JRY2lqbE5hV3V4VmRCUUQ2NVdpUzlGRXgrVGJ4UytJc2g5QTI5eVxuVmZtWUgwVHhKOUFqM1BzZnBpYUpmdGJSaGloY1FubGRFTzZzeHc1REhaL2ZRYnhFWWxidmhHc2YvTExtcS9rTFxuR2ZrZVhjQk5GOFhycUVodXo0TVYrS0RrcTUxOUFjb29GMjIzTTlUaDNSZlZ5ODkxSFRjbTA0K0ZOTWVHVE1sV1xuTldqVVlyTjFBZ01CQUFFQ2dnRUFBUEJtUFI3SEtLOW01S3dHa3d6MmxwNVFDRm96ZDJTYUNmVmJBOXFnam1CbFxuSnBrc0M2Z2J5TkpPQUE2dG4yN3M4WThmbEs1RjdNT2swK3BJdnJFUzRwVmRQQkc3Z3JreTFUdEtoTnNGYjhjcFxuVGtxY01la0V3U25uaWt5Q1FJOGtnTXlETWFwRzNBSlh1b2NveWllRm1XV0F2ZjlVWWp6by9QMUQyOUxGRTdUUVxud2pZalhvTEFoMXliMXFFTUYyUzdRMDJ5MXE1ZEhNbkRNQnQySEpiSVRxNjJESjE0RGFaNzVDcEVGUUVZeWV3RlxuaTZPaFdnNGY1RTBLTWZkdGVOMHZ4QUNXeVptSndSb0Q4Rnpja3BJQnkyWTdVdzNHcHRnTEx3UVh2MXVWSi9WdlxuTDEvR24rZXNPOE5VWFcwMUhWbHBsbTNpZlBWMloxM0NiZ1MydnJwZmtRS0JnUURQMHdibW5jZDJGeWs1RmRpNVxubUxrRm1hdWdRNzljQlpNVFlmb01mMGt2eTV0LzdKZU9zQXl3eUxicHc5VHpxU0pXeks4dlgzYXp3Yk1sUE8zVlxuZHVjcXRvY3R1aS9qcTlINllReWQ0ZnF1S05lOGpKMDE5bXdOVEZ1YkZaU0x3b3RLdnlQOHByU1ZiSGM1aEdaTVxuYzIzTC8yRHlKdSswMEhieVRKR0g0QWw0WFFLQmdRREdpbTdlZTBoZ0xoU3lVOSt3dG1wc01hajlHMkpWTy9icFxubmJsT25SajVQQnVGdnJDVkpFSzRlWDhFT2U4R3BrcGxLbmVubWFZMDVnZDZoS0pHQ05JK2lJanlMa1VIa05MUVxuN3BKZlRlQ0pHUEpXZ1VmVllRUG5EYlBBeVN1Q09YUFV6QmVJOTdicUJQR1NSZy9qMlRkelRqMlh4amo4UU5nWlxuajZJLzNMRVYrUUtCZ1FDa0YzbGhhYjd0N1FldGZTUnNGcnd3UWMrVGNTcU0zQkh1d2ZPUEhvbUk1WGpZSHRUalxuNHZtQ05Gaklac21qd2kzTTN6eUxhUkx1aDhpTlpIaGRqYzZrbVE1TytxMkpWRWN0TEtlcm1adzNHeVNNU1hKd1xuQXl2NXJBckFmdCtWSW55Yy9pTEtBRTZobE16bWF6WGlzMWxFTTFZMm5LdXoxczIwTHVUUnBnR1VPUUtCZ0hUaFxuem45ZjZLM21zdnlBOERHaVVtaTdtNWJXWmo5emU5cndwY1VvS3ltZlB6eXZsRmxZN1lhWTBEUDJ2MGNVNHJ0SVxuRXdVeUtXeis5dXdqNVR5QnVQUmpnT3ZDWFpVa3AxZWsrN3JycUFKT0UyemwweHBGY1B5M1RsbHlsUkNuTGcvYVxuendndGZSdXNLV05KcDlVbGJjV09EQ2lyNDZSdHNFcnNDa0s2Yys1UkFvR0FFSml2a29lY2dJWFFhVlQ5K2NQT1xuQWtHcWRDUzE1bGNiMkxRNVYwcEhtMG56ODBybWxGMWxGbHBCL3V5MTh6NGNkWFlmcjAycmhwTGkyM1Q3UHV5bFxuL3RLTlJmeHBmdFJWUnVyd1ZOQzlTWHJZcFNaSmJhRmRnMWlRQ1JXU2dmdDdBM3FQT1ZMa2hoejh6RWlMRmdtRVxuQXEvdnhZcUt0QXlYSmtlQTlhTEEyM0E9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLCJjbGllbnRfZW1haWwiOiJkYWlyeWZhcm0tc29ja2V0cy1zZXJ2ZXJAbWlsa3NoYWtlLWRldi1mYWY3Ny5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImNsaWVudF9pZCI6IjEwMDQ1NDkwMDEwNzU5NzUzMjQ3MyIsImF1dGhfdXJpIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCJ0b2tlbl91cmkiOiJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsImNsaWVudF94NTA5X2NlcnRfdXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kYWlyeWZhcm0tc29ja2V0cy1zZXJ2ZXIlNDBtaWxrc2hha2UtZGV2LWZhZjc3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwidW5pdmVyc2VfZG9tYWluIjoiZ29vZ2xlYXBpcy5jb20ifQ==' # !Sub '{{resolve:secretsmanager:MySecretName:SecretString:MySecretKey}}'
  Api:
    TracingEnabled: true
Resources:
  MyAuthApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Production
        Auth:
          DefaultAuthorizer: WalletAdminAuthorizer
          Authorizers:
            WalletAdminAuthorizer:
              FunctionArn: !GetAtt WalletAuthValidatorFunction.Arn
              AuthorizerResultTtlInSeconds: 0 # This disables caching
  WalletAuthValidatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wallet-gateway/
      Handler: app.walletAuthValidator
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  CreateWalletFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.createWallet  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        CreateWallet:
          Type: Api
          Properties:
            Path: /wallet
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  GetWalletFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.getWallet  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        GetWallet:
          Type: Api
          Properties:
            Path: /wallet
            Method: get
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  UpdateWalletFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.updateWallet  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        UpdateWallet:
          Type: Api
          Properties:
            Path: /wallet/update
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  PostTransactionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.postTransaction  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        PostTransaction:
          Type: Api
          Properties:
            Path: /transaction
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  PermaTransferFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.permaTransfer  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        PostTransaction:
          Type: Api
          Properties:
            Path: /permatransfer
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  ConfirmChargeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.confirmCharge  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        ConfirmCharge:
          Type: Api
          Properties:
            Path: /transaction/confirm-charge
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  GetTransactionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.getTransaction  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        GetTransaction:
          Type: Api
          Properties:
            Path: /transaction
            Method: get
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  RecallTransactionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.recallTransaction  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        RecallTransaction:
          Type: Api
          Properties:
            Path: /transaction/recall
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  CashOutTransactionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: wallet-gateway/  # Your code folder for create wallet
      Handler: app.cashOutTransaction  # Your handler function for create wallet
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Events:
        CashOutTransaction:
          Type: Api
          Properties:
            Path: /transaction/cashout
            Method: post
            RestApiId: !Ref MyAuthApi
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
